server.port=8083

# Resilience4j Circuit Breakers
resilience4j.circuitbreaker.configs.default.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.configs.default.sliding-window-size=10
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=5
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.configs.default.ignore-exceptions[0]=org.springframework.web.client.HttpClientErrorException
resilience4j.circuitbreaker.configs.default.ignore-exceptions[1]=java.lang.IllegalArgumentException

resilience4j.circuitbreaker.instances.catalog-get.base-config=default
resilience4j.circuitbreaker.instances.catalog-reserve.base-config=default
resilience4j.circuitbreaker.instances.users-get.base-config=default

# App Kafka Topics & Groups
app.kafka.topics.user-deleted=users.deleted.v1
app.kafka.topics.user-deleted-dlt=users.deleted.v1.dlt
app.kafka.topics.application-revoked=applications.revoked.v1
app.kafka.groups.user-deletion=adoption-service.user-deletion.v1

# Kafka Consumer Class Mapping
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.wise.adoption_service.adoption.messaging.UserDeletedV1
spring.kafka.consumer.properties.spring.json.use.type.headers=false