server.port=8082

# MongoDB Configs
storage.type=${STORAGE_TYPE:mongo}
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.auto-index-creation=true
spring.mongodb.uuid-representation=standard

# MinIO Configs
minio.url=${MINIO_URL}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-name=${MINIO_BUCKET:animals}

# Multipart Upload Limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:1GB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:1GB}
spring.servlet.multipart.file-size-threshold=${FILE_SIZE_THRESHOLD:1MB}
spring.servlet.multipart.location=${UPLOAD_TEMP_DIR:${java.io.tmpdir}}
server.tomcat.max-swallow-size=-1

# Logging Overrides
logging.level.org.springframework.security=DEBUG

# App Kafka Topics & Groups
app.kafka.topics.application-revoked=applications.revoked.v1
app.kafka.topics.application-revoked-dlt=applications.revoked.v1.dlt
app.kafka.groups.application-revoked=catalog-service.application-revoking.v1

# Kafka Consumer Class Mapping
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.wise.catalog_service.animal.messaging.ApplicationRevokedV1
spring.kafka.consumer.properties.spring.json.use.type.headers=false