server.port=8082
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
storage.type=${STORAGE_TYPE:mongo}
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.auto-index-creation=true
spring.mongodb.uuid-representation=standard
minio.url=${MINIO_URL}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-name=${MINIO_BUCKET:animals}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:1GB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:1GB}
spring.servlet.multipart.file-size-threshold=${FILE_SIZE_THRESHOLD:1MB}
spring.servlet.multipart.location=${UPLOAD_TEMP_DIR:${java.io.tmpdir}}
server.tomcat.max-swallow-size=-1
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.open-in-view=false
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public
logging.level.org.springframework.security=DEBUG

app.kafka.topics.application-revoked=applications.revoked.v1
app.kafka.groups.application-revoked=catalog-service.application-revoking.v1

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.wise.catalog_service.animal.messaging.ApplicationRevokedV1
spring.kafka.consumer.properties.spring.json.use.type.headers=false
