server.port=8081

# JWT & Refresh Token Expirations
security.jwt.access-token-ttl=15m
security.refresh-token.ttl=30d
security.refresh-token.cleanup-cron=0 0 3 * * *

# App Kafka Topics
app.kafka.topics.user-deleted=users.deleted.v1